// Diccionario español -> alto valyrio (se puede expandir fácilmente)
const diccionario = {
    "fuego": "dracarys",
    "dragón": "zaldrizes",
    "dragon": "zaldrizes",
    "no": "daor",
    "puede": "istagon",
    "matar": "dēmalion",
    "el": "se",
    "a": "na",
    "un": "nyke",
    "es": "ikagon",
    "yo": "nyke",
    "tu": "ao",
    "rey": "āeksio",
    "obedece": "dohaeras",
    "calma": "lykiri",
    "espera": "umbas",
    "atento": "rybas",
    "ven": "mazis",
    "venir": "mazis",
    "adelante": "naejot",
    "sigue": "naejot",
    "volar": "soves",
    "hombre": "vala",
    "niña": "riña",
    "niño": "taoba",
    "padre": "kepa",
    "madre": "muña",
    "rapido": "aderi",
    "atacar": "angos",
    "sentar": "demas",
    "atencion": "dookimarvose",
    "atención": "dookimarvose",
    "depositar": "elenas",
    "abajo": "embrot",
    "izquierda": "geptot",
    "bien": "gevi / hegnir",
    "beber": "iedrot",
    "volver": "inkot",
    "parar": "ioras",
    "mover": "jas",
    "comer": "kisas",
    "aterrizar": "ninkiot / parmot",
    "derecha": "paktot",
    "esquivar": "pales",
    "norte": "jelmor",  /*DIRECCIONES*/
    "este": "ñaqon",
    "sur": "vezor",
    "oeste": "endia",/*NUMEROS*/
    "cero": "daorun",
    "uno": "mere",
    "dos": "lanta",
    "tres": "hare",
    "cuatro": "izula",
    "cinco": "toma",
    "seis": "byre",
    "siete": "sikuda",
    "ocho": "jenqa",
    "nueve": "vore",
    "diez": "ampa",
    "cien": "gar",
    "mil": "pyrys",
    "gracias": "kirimvose",
    "si": "issa"
  };